const savedQueue=(()=>{try{return JSON.parse(localStorage.getItem('economicsReadingQueue')||'null')}catch{return null}})();
const state={catalog:[],issues:[],blogs:[],selected:new Set(savedQueue||['CR5b50a94eb4a48c'])};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noopener">${label} ↗</a>`:'<span>Link pending</span>';
function renderIssue(){const issue=state.issues[0];const packet=issue.public_packet?`<a class="primary" href="${esc(issue.public_packet)}">Download the complete 3-paper PDF · 35 pages ↓</a>`:'';const daily=document.querySelector('#daily-download');if(issue.public_packet)daily.href=issue.public_packet;document.querySelector('#brief').innerHTML=`<div><p class="eyebrow">The one-page view · ${esc(issue.issue_date)}</p><h2>${esc(issue.title)}</h2>${packet}</div><div><p>${esc(issue.trend)}</p><p><b>Combined packet:</b> one cover and synthesis page followed by selected pages from all three open-license articles in a single printable PDF.</p></div>`;document.querySelector('#issue-cards').innerHTML=issue.articles.map((x,i)=>`<article><div class="num">0${i+1} · ${esc(x.role)}</div><p class="eyebrow">${esc(x.paper.subtopic||x.paper.topic)}</p><h3>${esc(x.paper.title)}</h3><p class="summary">${esc(x.summary)}</p>${link(x.paper.url,'Read at source')}</article>`).join('')}
function renderCatalog(){const q=document.querySelector('#search').value.toLowerCase(),topic=document.querySelector('#topic-filter').value,status=document.querySelector('#status-filter').value;const visible=state.catalog.filter(x=>(!topic||x.topic===topic)&&(!status||x.status===status)&&(!q||[x.title,x.authors,x.abstract,x.subtopic,x.source].join(' ').toLowerCase().includes(q)));document.querySelector('#result-count').textContent=visible.length;document.querySelector('#queue-count').textContent=state.selected.size;document.querySelector('#catalog').innerHTML=visible.map(x=>`<div class="catalog-card"><input type="checkbox" aria-label="Add ${esc(x.title)}" ${state.selected.has(x.id)?'checked':''} data-id="${esc(x.id)}"><div><span class="tag">${esc(x.status)} · ${esc(x.subtopic||x.topic)}</span><h3>${esc(x.title)}</h3><p>${esc(x.authors)}${x.year?' · '+esc(x.year):''} · ${esc(x.source)}</p></div><p class="abstract">${esc((x.abstract||'No abstract available.').slice(0,330))}${(x.abstract||'').length>330?'…':''}</p>${link(x.url,'Source')}</div>`).join('');document.querySelectorAll('.catalog-card input').forEach(el=>el.addEventListener('change',e=>{e.target.checked?state.selected.add(e.target.dataset.id):state.selected.delete(e.target.dataset.id);localStorage.setItem('economicsReadingQueue',JSON.stringify([...state.selected]));document.querySelector('#queue-count').textContent=state.selected.size}))}
function renderBlogs(){document.querySelector('#blogs').innerHTML=state.blogs.map(x=>`<div class="blog-card"><span class="tag">${esc(x.source)} · ${esc(x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.notes)}</p>${x.paper_title?`<span class="pair">Paired paper: ${esc(x.paper_title)} · ${esc(x.access_note)}</span>`:''}${link(x.blog_url,'Read explainer')} ${x.paper_url?link(x.paper_url,'Paper'):''}</div>`).join('')}
function openPrint(){const picks=state.catalog.filter(x=>state.selected.has(x.id));document.querySelector('#print-date').textContent=new Date().toLocaleDateString(undefined,{dateStyle:'long'});document.querySelector('#print-items').innerHTML=picks.length?picks.map(x=>`<article><p class="eyebrow">${esc(x.subtopic||x.topic)}</p><h3>${esc(x.title)}</h3><p>${esc(x.authors)} · ${esc(x.year)} · ${esc(x.source)}</p><p>${esc(x.abstract||'')}</p></article>`).join(''):'<p>Select papers from the library first.</p>';document.querySelector('#print-sheet').classList.add('open')}
Promise.all(['data/catalog.json','data/issues.json','data/blogs.json'].map(u=>fetch(u).then(r=>r.json()))).then(([catalog,issues,blogs])=>{Object.assign(state,{catalog,issues,blogs});const topics=[...new Set(catalog.map(x=>x.topic))].sort();document.querySelector('#topic-filter').innerHTML+=[...topics].map(x=>`<option>${esc(x)}</option>`).join('');renderIssue();renderCatalog();renderBlogs();document.querySelector('#refresh-date').textContent=new Date().toLocaleDateString();});
['search','topic-filter','status-filter'].forEach(id=>document.querySelector('#'+id).addEventListener('input',renderCatalog));document.querySelector('#print-queue').addEventListener('click',openPrint);document.querySelector('#close-print').addEventListener('click',()=>document.querySelector('#print-sheet').classList.remove('open'));